use_frameworks!

platform :ios, '9.0'

target 'AlertServiceLibrary_Example' do
  pod 'AlertServiceLibrary', :path => '../'

  target 'AlertServiceLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
